python main.py \
  --train_data_path "./data/AllNLI.tsv"\
  --dev_data_path "./data/stsbenchmark.tsv"\
  --test_data_path "./data/stsbenchmark.tsv"\
  --plm "./plm" \
  --save_path "./outputs" \
  --lr 2e-5 \
  --num_epochs 1 \
  --train_batch_size 128 \
  --dev_batch_size 128 \
  --max_seq_length 75